Compass Display Name: Compass
Compass Lore:
  - "This is the first lore line"
  - "This is the second lore line"
Compass Menu: example_menu

Menus:
  example_menu:
    Title: Example Menu
    Number of Slots: 9
    Filler Material: BLACK_STAINED_GLASS_PANE
    Slots:
      1:
        Material: RED_WOOL
        Display Name: "The display name for the wool"
        Lore:
          - "This is the first lore line"
        Amount: 1
        Actions:
          Commands:
            - "heal %player%"
            - "fly %player%"
          GUI: example_menu2
  example_menu2:
    Title: Example Menu2
    Number of Slots: 9
    Filler Material: BLACK_STAINED_GLASS_PANE
    Slots:
      1:
        Material: BLACK_WOOL
        Amount: 1
        Display Name: "The display name for the wool"
        Actions:
          Commands:
            - "heal %player%"
            - "fly %player%"
          GUI: example_menu2